---
title: "Dr. Brazel"
output: pdf_document
params:
  RAZ: RAZ
  RAN: RAN
  RAB: RAB
  RAZB: RAZB
  directN: directN
  directZ: directZ
  directB: directB
  TWH: TWH
  SJH: SJH
  TWHZ: TWHZ
  SJHZ: SJHZ
---

```{r libraries, include=FALSE, echo=FALSE}
library(readr)
library(tidyverse)
library(lubridate)
library(stringr)
library(knitr)
library(tibble)
```



```{r digits, messages =FALSE, include=FALSE, warnings = FALSE, echo=FALSE}
options(pillar.sigfig = 2)
```

```{r RAs, messages =FALSE, include=FALSE, warnings = FALSE, echo=FALSE}
# Detect skiped lines
RAs <- read_lines(params$RAB)
skip_h <- which(str_detect(RAs, "\"Group Number\"")) - 1
RA_h <- read_csv(params$RAB, skip = skip_h, col_names = FALSE, n_max = 10)
Dr <- RA_h$X2[RA_h$X1 == "Payee"]
ra_date <- dmy(RA_h$X2[RA_h$X1 == "Payment Date"])
skip <- which(str_detect(RAs, "Accepted\\sClaims"))

# Read CSV
RAs <- read_csv(params$RAB, skip = skip, guess_max = 3000)

# Clean CSV
RAs <- RAs[is.na(RAs$`First Name`) == FALSE,]
RAs <- RAs[!str_detect(RAs$NS, pattern =  "NS"),]
RAs$`Amt Paid`[is.na(RAs$`Amt Paid`)] <- 0
RAs$`Amt Submitted`[is.na(RAs$`Amt Submitted`)] <- 0


RAs <- RAs %>% select(`OHIP Claim #`, `Service Code`,
                      `Service Date`, NS, `Amt Submitted`,
                      `Amt Paid`, `Expl Code`) %>%
  mutate(`Service Date` = dmy(`Service Date`),
         `Amt Paid` = str_remove(RAs$`Amt Paid`, pattern = "\\$"),
      `Amt Submitted` = str_remove(RAs$`Amt Submitted`, pattern = "\\$"),
         `Amt Paid` = as.numeric(paste(`Amt Paid`)),
          `Amt Submitted` = as.numeric(paste(`Amt Submitted`)),
         Type = ifelse(RAs$`Service Code` == "G432A" |
                       RAs$`Service Code` == "G858A" |
                       RAs$`Service Code` == "G810A" |
                       RAs$`Service Code` == "G811A" |
                       RAs$`Service Code` == "G818A" |
                       RAs$`Service Code` == "G820A" |
                       RAs$`Service Code` == "G813A" |
                       RAs$`Service Code` == "J108C" |                                               
                       RAs$`Service Code` == "J108B",
                       "OHIP.Test",
                       "OHIP.Clinic"))
RAs$`Amt Paid`[is.na(RAs$`Amt Paid`)] <- 0
RAs$`Amt Submitted`[is.na(RAs$`Amt Submitted`)] <- 0

RAs <- RAs[is.na(RAs$`Service Code`) == FALSE,]
```

# `r paste(Dr,"'s" ," remittance file paid by OHIP on ", ra_date, sep = "")`

```{r direct, messages =FALSE, include=FALSE, warnings = FALSE, echo=FALSE}
direct <- read_csv(params$directB, skip = 2)
direct <- direct[str_detect(direct$DR, "SB|SB01"),]
direct <- direct[,c("PID", "Serv Code", "Paid", "S Date", "NS")]

direct <- direct %>% 
  mutate(S.Date = dmy(`S Date`), 
         Type = ifelse(direct$`Serv Code` == "G432A" |
                       direct$`Serv Code` == "G858A" |
                       direct$`Serv Code` == "G810A" |
                       direct$`Serv Code` == "G811A" |
                       direct$`Serv Code` == "G818A" |
                       direct$`Serv Code` == "G820A" |
                       direct$`Serv Code` == "G813A" |
                       direct$`Serv Code` == "VF" |
		                   direct$`Serv Code` == "OCT" |
		                   direct$`Serv Code` == "TOPOGRAPHY"|
		                   direct$`Serv Code` == "IOL"|
		                   direct$`Serv Code` == "HRT",
		                   "Direct.Test", 
		                   "Direct.Clinic")) %>%
  filter(month(S.Date) == month(ra_date %m-% months(1)))

direct$Paid[is.na(direct$Paid)] <- 0 
direct$`S Date` <- NULL
```

```{r sums, messages =FALSE, include=FALSE, warnings = FALSE, echo=FALSE}
ohip_sums <- RAs %>% group_by(Type) %>% summarize(sum = sum(`Amt Paid`))
direct_sums <- direct %>% group_by(Type) %>% summarize(sum = sum(Paid))
Total <- rbind(ohip_sums, direct_sums)

`Sum Clinic` <- sum(Total$sum[str_detect(Total$Type, pattern = "Clinic")])
`Sum Test` <- sum(Total$sum[str_detect(Total$Type, pattern = "Test")])

Unpaid <- RAs[RAs$`Amt Paid` == 0,] %>% group_by(`Service Code`) %>%
  summarise(`Number of Claims` = n(),
            `Unpaid Sum` = sum(`Amt Submitted`)) %>%
  arrange(desc(`Unpaid Sum`))

RAs$Diff <- RAs$`Amt Submitted` - RAs$`Amt Paid`

`Partially Paid` <- RAs[RAs$Diff != 0 & RAs$`Amt Paid` != 0,] %>%
  group_by(`Service Code`) %>%
  summarise(`Number of Claims` = n(), Submitted = sum(`Amt Submitted`),
            Paid = sum(`Amt Paid`), Unpaid = sum(Diff)) %>%
  arrange(desc(Unpaid))

unpt <- sum(Unpaid$`Unpaid Sum`)
punpt <- sum(`Partially Paid`$Unpaid)
```

# Totals

```{r Total, echo=FALSE}
kable(Total)
kable(tibble(`Sum Clinic`, `Sum Test`))
```

# Unpaid Claims
`r paste("Total unpaid =", round(unpt, digits = 2))`

```{r Unpaid, echo=FALSE}
kable(Unpaid)
```

\newpage

# Partially Paid Claims
`r paste("Total unpaid =", round(punpt, digits = 2))`

```{r PUnpaid, echo=FALSE}
kable(`Partially Paid`)
```

# OHIP
```{r ohip sums, echo=FALSE}
RAs$Diff <- NULL
RAs$`Expl Code` <- NULL

#kable(arrange(RAs, Type))
kable(ohip_sums)
```

## Payment per code
```{r OHIP Total by code, warnings = FALSE, echo=FALSE}
# Summary
#kable(RAs)

kable(RAs %>% group_by(`Service Code`) %>% 
        summarize("Number of services" = n(),
                  "Total" = sum(`Amt Paid`)) %>%
      arrange(desc(Total)))

```

## Payment per date
```{r OHIP Total by date, warnings = FALSE, echo=FALSE}
kable(RAs %>% 
        group_by(`Service Date`) %>% 
        summarize("Weekday" = weekdays(unique(`Service Date`)),
                  "Number of services" = n(),
                  "Total" = sum(`Amt Paid`)))
     

```

\newpage


# Direct
```{r direct sums, echo=FALSE}
#kable(arrange(direct, Type))
kable(direct_sums)
```

## Payment per code
```{r Direct Total by code, warnings = FALSE, echo=FALSE}
kable(direct %>% group_by(`Serv Code`) %>% 
        summarize("Number of services" = n(),
                  "Total" = sum(Paid)) %>%
      arrange(desc(Total)))
```

## Payment per date
```{r Direct Total by date, warnings = FALSE, echo=FALSE}
kable(direct %>% group_by(S.Date) %>% 
        summarize("Weekday" = weekdays(unique(S.Date)),
                  "Number of services" = n(),
                  "Total" = sum(Paid)))
```


